import os
import sqlite3
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Any

from dotenv import load_dotenv

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None

load_dotenv()

DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("POSTGRES_PRISMA_URL")
)

BASE_DIR = Path(__file__).resolve().parent
logger = logging.getLogger("veterinaria.agenda")

TIEMPOS_CIRUGIA = {
    "gato_macho": 12,
    "gata_hembra": 15,
    "perro_macho": 30,
    "perra_0_10": 45,
    "perra_10_20": 50,
    "perra_20_30": 60,
    "perra_30_40": 60,
    "perra_40_mas": 70,
}

CAPACIDAD_DIARIA = 240
MAX_PERROS_DIA = 2
DIAS_OPERATIVOS = [0, 1, 2, 3]  # lunes a jueves


# =========================
# DB HELPERS
# =========================

def is_sqlite() -> bool:
    return bool(DATABASE_URL and DATABASE_URL.startswith("sqlite:///"))


def is_postgres() -> bool:
    return bool(
        DATABASE_URL
        and (
            DATABASE_URL.startswith("postgresql://")
            or DATABASE_URL.startswith("postgres://")
        )
    )


def get_sqlite_path() -> str:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL no está configurada.")

    raw_path = DATABASE_URL.replace("sqlite:///", "", 1)
    path = Path(raw_path)

    if not path.is_absolute():
        path = BASE_DIR / path

    return str(path)


def get_connection():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL no está configurada.")

    if is_sqlite():
        db_path = get_sqlite_path()
        conn = sqlite3.connect(db_path, timeout=10)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        return conn

    if is_postgres():
        if psycopg is None or dict_row is None:
            raise RuntimeError("Dependencia psycopg no disponible en runtime.")
        try:
            return psycopg.connect(DATABASE_URL, row_factory=dict_row)
        except Exception as exc:
            logger.exception("Error conectando a Postgres.")
            raise RuntimeError(f"No se pudo conectar a Postgres: {exc}") from exc

    raise RuntimeError(f"Formato de DATABASE_URL no soportado: {DATABASE_URL}")


def row_to_dict(row: Any) -> Optional[dict]:
    if row is None:
        return None
    if isinstance(row, dict):
        return row
    try:
        return dict(row)
    except Exception:
        return None


def rows_to_dicts(rows: list[Any]) -> list[dict]:
    resultado = []
    for row in rows:
        as_dict = row_to_dict(row)
        if as_dict is not None:
            resultado.append(as_dict)
    return resultado


def sql(query_sqlite: str, query_postgres: str) -> str:
    return query_sqlite if is_sqlite() else query_postgres


def paramstyle(query: str) -> str:
    if is_sqlite():
        return query.replace("%s", "?")
    return query


def execute_fetchone(query: str, params: tuple = ()) -> Optional[dict]:
    conn = get_connection()
    try:
        c = conn.cursor()
        c.execute(paramstyle(query), params)
        row = c.fetchone()
        return row_to_dict(row)
    finally:
        conn.close()


def execute_fetchall(query: str, params: tuple = ()) -> list[dict]:
    conn = get_connection()
    try:
        c = conn.cursor()
        c.execute(paramstyle(query), params)
        rows = c.fetchall()
        return rows_to_dicts(rows)
    finally:
        conn.close()


# =========================
# INIT DB
# =========================

def init_db():
    conn = get_connection()
    try:
        c = conn.cursor()

        c.execute(sql(
            """
            CREATE TABLE IF NOT EXISTS clientes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nombre TEXT NOT NULL,
                dni TEXT UNIQUE,
                telefono TEXT,
                email TEXT,
                direccion TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS clientes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                dni TEXT UNIQUE,
                telefono TEXT,
                email TEXT,
                direccion TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
            """
        ))

        c.execute(sql(
            """
            CREATE TABLE IF NOT EXISTS mascotas (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                cliente_id INTEGER NOT NULL,
                nombre TEXT NOT NULL,
                especie TEXT NOT NULL,
                sexo TEXT NOT NULL,
                peso REAL DEFAULT 0,
                edad INTEGER DEFAULT 0,
                tiene_microchip INTEGER DEFAULT 0,
                tiene_vacuna_rabia INTEGER DEFAULT 0,
                FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS mascotas (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id INTEGER NOT NULL,
                nombre TEXT NOT NULL,
                especie TEXT NOT NULL,
                sexo TEXT NOT NULL,
                peso REAL DEFAULT 0,
                edad INTEGER DEFAULT 0,
                tiene_microchip INTEGER DEFAULT 0,
                tiene_vacuna_rabia INTEGER DEFAULT 0,
                FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
            )
            """
        ))

        c.execute(sql(
            """
            CREATE TABLE IF NOT EXISTS citas (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                fecha TEXT NOT NULL,
                cliente_id INTEGER NOT NULL,
                mascota_id INTEGER NOT NULL,
                tipo_cirugia TEXT NOT NULL,
                minutos INTEGER NOT NULL,
                estado TEXT DEFAULT 'confirmada',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
                FOREIGN KEY (mascota_id) REFERENCES mascotas(id) ON DELETE CASCADE
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS citas (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                fecha TEXT NOT NULL,
                cliente_id INTEGER NOT NULL,
                mascota_id INTEGER NOT NULL,
                tipo_cirugia TEXT NOT NULL,
                minutos INTEGER NOT NULL,
                estado TEXT DEFAULT 'confirmada',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
                FOREIGN KEY (mascota_id) REFERENCES mascotas(id) ON DELETE CASCADE
            )
            """
        ))

        c.execute(sql(
            """
            CREATE TABLE IF NOT EXISTS cambios_cita (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                cliente_id INTEGER,
                mascota_id INTEGER,
                fecha_antigua TEXT,
                fecha_nueva TEXT,
                fecha_cambio TEXT
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS cambios_cita (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id INTEGER,
                mascota_id INTEGER,
                fecha_antigua TEXT,
                fecha_nueva TEXT,
                fecha_cambio TEXT
            )
            """
        ))

        # Índices útiles
        c.execute("CREATE INDEX IF NOT EXISTS idx_clientes_dni ON clientes(dni)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_mascotas_cliente_id ON mascotas(cliente_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_mascotas_cliente_nombre ON mascotas(cliente_id, nombre)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_citas_fecha_estado ON citas(fecha, estado)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_citas_mascota_estado ON citas(mascota_id, estado)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_citas_cliente_fecha_estado ON citas(cliente_id, fecha, estado)")

        conn.commit()
    finally:
        conn.close()


def db_healthcheck() -> dict:
    try:
        conn = get_connection()
        try:
            c = conn.cursor()
            c.execute("SELECT 1 AS ok")
            row = c.fetchone()
            row_dict = row_to_dict(row)
            return {"status": "ok", "ping": row_dict["ok"] if row_dict else None}
        finally:
            conn.close()
    except Exception as exc:
        return {"status": "error", "error": str(exc)}


# =========================
# CLIENTES
# =========================

def buscar_cliente_por_dni(dni: str) -> Optional[dict]:
    return execute_fetchone(
        "SELECT id, nombre, dni, telefono, email, direccion FROM clientes WHERE UPPER(dni) = %s",
        (dni.strip().upper(),),
    )


def buscar_cliente_por_nombre(nombre: str) -> Optional[dict]:
    return execute_fetchone(
        "SELECT id, nombre, dni, telefono, email, direccion FROM clientes WHERE LOWER(nombre) LIKE %s LIMIT 1",
        (f"%{nombre.strip().lower()}%",),
    )


def registrar_cliente(nombre: str, dni: str, telefono: str, email: str, direccion: str) -> tuple[bool, str]:
    conn = get_connection()
    try:
        c = conn.cursor()

        if is_sqlite():
            c.execute(
                """
                INSERT INTO clientes (nombre, dni, telefono, email, direccion)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    nombre.strip(),
                    dni.strip().upper(),
                    telefono.strip(),
                    email.strip(),
                    direccion.strip(),
                ),
            )
            cliente_id = c.lastrowid
        else:
            c.execute(
                """
                INSERT INTO clientes (nombre, dni, telefono, email, direccion)
                VALUES (%s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    nombre.strip(),
                    dni.strip().upper(),
                    telefono.strip(),
                    email.strip(),
                    direccion.strip(),
                ),
            )
            row = c.fetchone()
            row_dict = row_to_dict(row)
            cliente_id = row_dict["id"] if row_dict else None

        conn.commit()
        return True, str(cliente_id) if cliente_id is not None else ""
    except Exception as e:
        error_text = str(e).lower()
        if "duplicate key value" in error_text or "unique constraint failed" in error_text:
            return False, "Ya existe un cliente con ese DNI."
        raise
    finally:
        conn.close()


# =========================
# MASCOTAS
# =========================

def listar_mascotas_cliente(cliente_id: int) -> list[dict]:
    rows = execute_fetchall(
        """
        SELECT id, cliente_id, nombre, especie, sexo, peso, edad, tiene_microchip, tiene_vacuna_rabia
        FROM mascotas
        WHERE cliente_id = %s
        ORDER BY nombre
        """,
        (cliente_id,),
    )

    mascotas = []
    for row in rows:
        mascotas.append({
            "id": row["id"],
            "cliente_id": row["cliente_id"],
            "nombre": row["nombre"],
            "especie": row["especie"],
            "sexo": row["sexo"],
            "peso": row["peso"],
            "edad": row["edad"],
            "tiene_microchip": bool(row["tiene_microchip"]),
            "tiene_vacuna_rabia": bool(row["tiene_vacuna_rabia"]),
        })
    return mascotas


def buscar_mascota_cliente_por_nombre(cliente_id: int, nombre: str) -> Optional[dict]:
    row = execute_fetchone(
        """
        SELECT id, cliente_id, nombre, especie, sexo, peso, edad, tiene_microchip, tiene_vacuna_rabia
        FROM mascotas
        WHERE cliente_id = %s AND LOWER(nombre) = %s
        LIMIT 1
        """,
        (cliente_id, nombre.strip().lower()),
    )

    if not row:
        return None

    return {
        "id": row["id"],
        "cliente_id": row["cliente_id"],
        "nombre": row["nombre"],
        "especie": row["especie"],
        "sexo": row["sexo"],
        "peso": row["peso"],
        "edad": row["edad"],
        "tiene_microchip": bool(row["tiene_microchip"]),
        "tiene_vacuna_rabia": bool(row["tiene_vacuna_rabia"]),
    }


def registrar_mascota(
    cliente_id: int,
    nombre: str,
    especie: str,
    sexo: str,
    peso: float,
    edad: int,
    microchip: bool,
    vacuna_rabia: bool,
) -> int:
    conn = get_connection()
    try:
        c = conn.cursor()

        if is_sqlite():
            c.execute(
                """
                INSERT INTO mascotas (
                    cliente_id, nombre, especie, sexo, peso, edad, tiene_microchip, tiene_vacuna_rabia
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    cliente_id,
                    nombre.strip().lower(),
                    especie.strip().lower(),
                    sexo.strip().lower(),
                    float(peso),
                    int(edad),
                    int(microchip),
                    int(vacuna_rabia),
                ),
            )
            mascota_id = c.lastrowid
        else:
            c.execute(
                """
                INSERT INTO mascotas (
                    cliente_id, nombre, especie, sexo, peso, edad, tiene_microchip, tiene_vacuna_rabia
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    cliente_id,
                    nombre.strip().lower(),
                    especie.strip().lower(),
                    sexo.strip().lower(),
                    float(peso),
                    int(edad),
                    int(microchip),
                    int(vacuna_rabia),
                ),
            )
            row = c.fetchone()
            row_dict = row_to_dict(row)
            mascota_id = row_dict["id"] if row_dict else 0

        conn.commit()
        return int(mascota_id) if mascota_id is not None else 0
    finally:
        conn.close()


# =========================
# CITAS Y REGLAS
# =========================

def existe_cita_mascota(fecha_str: str, mascota_id: int) -> bool:
    row = execute_fetchone(
        """
        SELECT COUNT(*) AS total
        FROM citas
        WHERE fecha = %s AND mascota_id = %s AND estado = 'confirmada'
        """,
        (fecha_str, mascota_id),
    )
    return bool(row and row["total"] > 0)


def obtener_cita_confirmada_por_mascota(mascota_id: int) -> Optional[str]:
    row = execute_fetchone(
        """
        SELECT fecha
        FROM citas
        WHERE mascota_id = %s AND estado = 'confirmada'
        ORDER BY fecha DESC
        LIMIT 1
        """,
        (mascota_id,),
    )
    return row["fecha"] if row else None


def obtener_todas_citas_confirmadas_por_mascota(mascota_id: int) -> list[str]:
    rows = execute_fetchall(
        """
        SELECT fecha
        FROM citas
        WHERE mascota_id = %s AND estado = 'confirmada'
        ORDER BY fecha
        """,
        (mascota_id,),
    )
    return [row["fecha"] for row in rows]


def es_dia_operativo(fecha_str: str) -> tuple[bool, str]:
    try:
        fecha = datetime.strptime(fecha_str, "%Y-%m-%d").date()
    except ValueError:
        return False, "Formato de fecha incorrecto."

    if fecha.weekday() not in DIAS_OPERATIVOS:
        dias = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]
        return False, f"El {dias[fecha.weekday()]} no es día operativo. Las cirugías son de lunes a jueves."

    return True, ""


def get_minutos_ocupados(fecha_str: str, conn=None) -> int:
    close_after = False
    if conn is None:
        conn = get_connection()
        close_after = True

    try:
        c = conn.cursor()
        c.execute(
            paramstyle(
                "SELECT COALESCE(SUM(minutos), 0) AS total FROM citas WHERE fecha = %s AND estado = 'confirmada'"
            ),
            (fecha_str,),
        )
        row = c.fetchone()
        row_dict = row_to_dict(row)
        return (row_dict["total"] if row_dict else 0) or 0
    finally:
        if close_after:
            conn.close()


def get_perros_dia(fecha_str: str, conn=None) -> int:
    close_after = False
    if conn is None:
        conn = get_connection()
        close_after = True

    try:
        c = conn.cursor()
        c.execute(
            paramstyle(
                """
                SELECT COUNT(*) AS total
                FROM citas c
                JOIN mascotas m ON c.mascota_id = m.id
                WHERE c.fecha = %s AND c.estado = 'confirmada' AND m.especie = 'perro'
                """
            ),
            (fecha_str,),
        )
        row = c.fetchone()
        row_dict = row_to_dict(row)
        return (row_dict["total"] if row_dict else 0) or 0
    finally:
        if close_after:
            conn.close()


def cliente_tiene_citas_en_fecha(fecha_str: str, cliente_id: int) -> int:
    row = execute_fetchone(
        """
        SELECT COUNT(*) AS total
        FROM citas
        WHERE fecha = %s AND cliente_id = %s AND estado = 'confirmada'
        """,
        (fecha_str, cliente_id),
    )
    return (row["total"] if row else 0) or 0


def verificar_disponibilidad(fecha_str: str, tipo_cirugia: str) -> tuple[bool, str]:
    operativo, msg = es_dia_operativo(fecha_str)
    if not operativo:
        return False, msg

    minutos = TIEMPOS_CIRUGIA.get(tipo_cirugia, 30)
    ocupados = get_minutos_ocupados(fecha_str)

    if ocupados + minutos > CAPACIDAD_DIARIA:
        restantes = CAPACIDAD_DIARIA - ocupados
        return False, f"No hay disponibilidad. Solo quedan {restantes} min."

    if "perro" in tipo_cirugia or "perra" in tipo_cirugia:
        perros = get_perros_dia(fecha_str)
        if perros >= MAX_PERROS_DIA:
            return False, "Ese día ya tiene 2 perros programados."

    return True, "Disponible"


def reservar_cita(fecha_str: str, cliente_id: int, mascota_id: int, tipo_cirugia: str) -> tuple[bool, str]:
    operativo, msg = es_dia_operativo(fecha_str)
    if not operativo:
        return False, msg

    minutos = TIEMPOS_CIRUGIA.get(tipo_cirugia, 30)

    conn = get_connection()
    try:
        c = conn.cursor()

        # Transacción más fuerte en SQLite para reducir carreras
        if is_sqlite():
            c.execute("BEGIN IMMEDIATE")

        c.execute(
            paramstyle(
                """
                SELECT COUNT(*) AS total
                FROM citas
                WHERE fecha = %s AND mascota_id = %s AND estado = 'confirmada'
                """
            ),
            (fecha_str, mascota_id),
        )
        row = c.fetchone()
        row_dict = row_to_dict(row)
        if row_dict and row_dict["total"] > 0:
            conn.rollback()
            return False, "La mascota ya tiene una cita confirmada en esa fecha."

        ocupados = get_minutos_ocupados(fecha_str, conn=conn)
        if ocupados + minutos > CAPACIDAD_DIARIA:
            conn.rollback()
            restantes = CAPACIDAD_DIARIA - ocupados
            return False, f"No hay disponibilidad. Solo quedan {restantes} min."

        if "perro" in tipo_cirugia or "perra" in tipo_cirugia:
            perros = get_perros_dia(fecha_str, conn=conn)
            if perros >= MAX_PERROS_DIA:
                conn.rollback()
                return False, "Ese día ya tiene 2 perros programados."

        c.execute(
            paramstyle(
                """
                INSERT INTO citas (fecha, cliente_id, mascota_id, tipo_cirugia, minutos, estado)
                VALUES (%s, %s, %s, %s, %s, 'confirmada')
                """
            ),
            (fecha_str, cliente_id, mascota_id, tipo_cirugia, minutos),
        )

        conn.commit()
        return True, "Cita reservada correctamente."
    except Exception as e:
        try:
            conn.rollback()
        except Exception:
            pass
        return False, f"Error de base de datos: {str(e)}"
    finally:
        conn.close()


def listar_citas(fecha_str: Optional[str] = None) -> list[dict]:
    conn = get_connection()
    try:
        c = conn.cursor()
        if fecha_str:
            c.execute(
                paramstyle("SELECT * FROM citas WHERE fecha = %s ORDER BY fecha"),
                (fecha_str,),
            )
        else:
            c.execute("SELECT * FROM citas ORDER BY fecha")

        rows = c.fetchall()
        return rows_to_dicts(rows)
    finally:
        conn.close()


# =========================
# DISPONIBILIDAD REAL
# =========================

def fecha_es_reservable(fecha: datetime.date) -> bool:
    return fecha.weekday() in DIAS_OPERATIVOS


def formatear_fecha_visual(fecha: datetime.date) -> str:
    dias_semana = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]
    meses = [
        "enero", "febrero", "marzo", "abril", "mayo", "junio",
        "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre",
    ]
    return f"{dias_semana[fecha.weekday()]} {fecha.day} de {meses[fecha.month - 1]} de {fecha.year}"


def get_fechas_disponibles_reales(tipo_cirugia: str, limite: int = 5) -> list[dict]:
    resultados = []
    hoy = datetime.now().date()
    dia = hoy

    while len(resultados) < limite:
        dia += timedelta(days=1)

        if not fecha_es_reservable(dia):
            continue

        fecha_str = dia.strftime("%Y-%m-%d")
        disponible, _ = verificar_disponibilidad(fecha_str, tipo_cirugia)

        if disponible:
            resultados.append({
                "fecha": fecha_str,
                "texto": formatear_fecha_visual(dia),
                "tipo_cirugia": tipo_cirugia,
            })

    return resultados


def contar_citas_por_dia(fecha: str):
    conn = get_connection()
    try:
        c = conn.cursor()
        c.execute(
            paramstyle(
                """
                SELECT tipo_cirugia FROM citas
                WHERE fecha = %s AND estado = 'confirmada'
                """
            ),
            (fecha,),
        )

        resultados = c.fetchall()
        filas = rows_to_dicts(resultados)

        total = len(filas)
        hembras = sum(1 for r in filas if "hembra" in r["tipo_cirugia"])
        grandes = sum(1 for r in filas if "30" in r["tipo_cirugia"] or "40" in r["tipo_cirugia"])

        return total, hembras, grandes
    finally:
        conn.close()


def registrar_cambio_cita(cliente_id, mascota_id, fecha_antigua, fecha_nueva):
    conn = get_connection()
    try:
        c = conn.cursor()
        c.execute(
            paramstyle(
                """
                INSERT INTO cambios_cita
                (cliente_id, mascota_id, fecha_antigua, fecha_nueva, fecha_cambio)
                VALUES (%s, %s, %s, %s, %s)
                """
            ),
            (cliente_id, mascota_id, fecha_antigua, fecha_nueva, datetime.now().isoformat()),
        )
        conn.commit()
    finally:
        conn.close()


def cancelar_cita_confirmada_por_mascota(mascota_id: int) -> bool:
    conn = get_connection()
    try:
        c = conn.cursor()
        c.execute(
            paramstyle(
                """
                UPDATE citas
                SET estado = 'cancelada'
                WHERE mascota_id = %s AND estado = 'confirmada'
                """
            ),
            (mascota_id,),
        )
        affected = c.rowcount
        conn.commit()
        return affected > 0
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        return False
    finally:
        conn.close()


if DATABASE_URL:
    logger.info(
        "Startup DB env detectada. source=%s",
        "DATABASE_URL" if os.getenv("DATABASE_URL") else (
            "POSTGRES_URL" if os.getenv("POSTGRES_URL") else "POSTGRES_PRISMA_URL"
        ),
    )
    try:
        init_db()
        logger.info("Init DB completada correctamente.")
    except Exception:
        logger.exception("Init DB falló durante startup.")