import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg.rows import dict_row


ROOT = Path(__file__).resolve().parents[1]
SQLITE_PATH = ROOT / "agenda.db"
DATABASE_URL = os.getenv("DATABASE_URL")


def _connect_sqlite() -> sqlite3.Connection:
    if not SQLITE_PATH.exists():
        raise FileNotFoundError(f"No existe SQLite en {SQLITE_PATH}")
    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _connect_postgres():
    if not DATABASE_URL:
        raise RuntimeError("Define DATABASE_URL antes de migrar.")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def _fetch_count_sqlite(conn: sqlite3.Connection, table: str) -> int:
    try:
        row = conn.execute(f"SELECT COUNT(*) AS total FROM {table}").fetchone()
        return int(row["total"])
    except sqlite3.OperationalError:
        return 0


def _fetch_count_postgres(conn, table: str) -> int:
    with conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) AS total FROM {table}")
        return int(cur.fetchone()["total"])


def migrate() -> None:
    sqlite_conn = _connect_sqlite()
    pg_conn = _connect_postgres()

    try:
        with pg_conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS clientes (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre TEXT NOT NULL,
                    dni TEXT UNIQUE,
                    telefono TEXT,
                    email TEXT,
                    direccion TEXT,
                    created_at TEXT DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS mascotas (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
                    nombre TEXT NOT NULL,
                    especie TEXT NOT NULL,
                    sexo TEXT NOT NULL,
                    peso REAL DEFAULT 0,
                    edad INTEGER DEFAULT 0,
                    tiene_microchip INTEGER DEFAULT 0,
                    tiene_vacuna_rabia INTEGER DEFAULT 0
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS citas (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fecha TEXT NOT NULL,
                    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
                    mascota_id INTEGER NOT NULL REFERENCES mascotas(id),
                    tipo_cirugia TEXT NOT NULL,
                    minutos INTEGER NOT NULL,
                    estado TEXT DEFAULT 'confirmada',
                    created_at TEXT DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS cambios_cita (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_id INTEGER,
                    mascota_id INTEGER,
                    fecha_antigua TEXT,
                    fecha_nueva TEXT,
                    fecha_cambio TEXT
                )
                """
            )

        tablas = ["clientes", "mascotas", "citas", "cambios_cita"]
        for tabla in tablas:
            try:
                rows = sqlite_conn.execute(f"SELECT * FROM {tabla}").fetchall()
            except sqlite3.OperationalError:
                continue
            if not rows:
                continue

            columnas = rows[0].keys()
            placeholders = ", ".join(["%s"] * len(columnas))
            col_list = ", ".join(columnas)

            with pg_conn.cursor() as cur:
                for row in rows:
                    values = [row[col] for col in columnas]
                    cur.execute(
                        f"INSERT INTO {tabla} ({col_list}) VALUES ({placeholders}) ON CONFLICT DO NOTHING",
                        values,
                    )
                if "id" in columnas:
                    cur.execute(
                        f"SELECT setval(pg_get_serial_sequence('{tabla}', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM {tabla}"
                    )

        pg_conn.commit()

        print("Migración completada. Conteos:")
        for tabla in tablas:
            sqlite_total = _fetch_count_sqlite(sqlite_conn, tabla)
            pg_total = _fetch_count_postgres(pg_conn, tabla)
            print(f"- {tabla}: sqlite={sqlite_total}, postgres={pg_total}")

    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    migrate()
